[package]
name = "memlayout"
version = "0.1.0"
edition = "2021"

[features]
default = ["dwarf", "runtime"]
cranelift = ["wasmer/cranelift", "wasmer-compiler-cranelift/disable-probestack"]
singlepass = ["wasmer/singlepass", "wasmer-compiler-singlepass/disable-probestack"]
llvm = ["wasmer/llvm", "wasmer-compiler-llvm"]
dwarf = ["gimli"]
runtime = ["wasmer"]

# Backend-Auswahl
#cranelift = ["wasmer-compiler-cranelift"]
#singlepass = ["wasmer-compiler-singlepass"]
#llvm = ["wasmer-compiler-llvm"]

[dependencies]
anyhow = "1.0"
byteorder = "1.5"
gimli = { version = "0.32", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
wasmer = { version = "6.0", optional = true }
wasmparser = "0.205"
wasmer-types = "6.0.1"

# Compiler-Backends explizit hinzuf√ºgen
wasmer-compiler-cranelift = { version = "6.0.1", optional = true }
wasmer-compiler-singlepass = { version = "6.0.1", optional = true }
wasmer-compiler-llvm = { version = "6.0.1", optional = true }
wasmer-compiler = "6.0.1"

[dependencies.wasmer-compiler-cranelift]
version = "6.0.1"
features = ["disable-probestack"]

[dependencies.wasmer-compiler-singlepass]
version = "6.0.1"
features = ["disable-probestack"]

[profile.dev]
debug = true
opt-level = 0
split-debuginfo = "packed"

[profile.release]
opt-level = 3
debug = true

